Primera implementación de la función de canáles dinámicos
acmfi/discord-bot pull request #21
Opened 2020-08-17 06:34 UTC by Formil

Cambios en bot.py para que cumpla la función de mostrar/esconder el canal de texto correspondiente a cada canal de voz, en este caso, suponiendo que el canal asignado a cada canal de voz es uno cuyo nombre es igual, pero acabado en "-texto", en este caso no siendo sensible a las mayúsculas o no. Sujeto a cambios obviamente, pero un acercamiento.

2020-08-17 18:03 UTC, JustAntoRS commented
Se nos esta yendo un poco de las manos el meter todo en bot.py, intenta separarlo en ficheros.

Mi idea es que bot.py sea el archivo que lanzamos y desde cada funcionalidad (como son muy diferentes entre si) que este en un fichero separado. Podemos verlo mas a fondo por Discord si hace falta

2020-09-10 14:37 UTC, JustAntoRS commented
Nada que añadir por mi parte, se puede hacer merge o falta algun commit por agregar a la PR?

2020-09-12 17:48 UTC, Formil commented
En principio se puede hacer merge, creo que si faltase algo sería documentarlo un poco.

2020-09-13 12:12 UTC, JustAntoRS reviewed
Hay un fichero binario en el commit, deberiamos borrar ese fichero binario ya que `__pycache__` deberia estar en `.gitignore`

2020-09-13 12:12 UTC, JustAntoRS commented on src/Extensions/dynamic-channels.py
> +        except discord.DiscordException as de:
Cuado lanza Discord esta excepcion? Y porque si la lanza simplemente no hacemos nada?

2020-09-13 12:12 UTC, JustAntoRS commented on src/Extensions/dynamic-channels.py
> +    async def on_voice_state_update(self,member,before,after):
Documentacion de la funcion, como minimo de que tipo son los argumentos y que representan

2020-09-13 12:12 UTC, JustAntoRS commented on src/Extensions/dynamic-channels.py
> +def setup(bot):
Espacio entre los import y la primera funcion pls, que me da toc xD

2020-09-15 06:53 UTC, Formil commented on src/Extensions/dynamic-channels.py
> +        except discord.DiscordException as de:
Era una excepción que puse como algo general, pero enseguida miro cuales puede lanzar en concreto y arreglo un poco eso.

2020-09-15 13:53 UTC, JustAntoRS requested changes
Hay varios archivos binarios en el commit, son los que acaban en `.pyc` estos archivos no deberian estar en el commit, eliminalos y pon la carpeta `__pycache__` que esta dentro de la carpeta `test` en el `.gitignore`

2020-09-15 13:53 UTC, JustAntoRS commented on .vscode/settings.json
> +}
Este fichero esta dentro de `.vscode` que es la carpeta que usa Visual Studio Code para temas de configuracion, metela dentro del `.gitignore` pls no la queremos en el rpeo

2020-09-15 13:53 UTC, JustAntoRS commented on src/bot.py
> +<<<<<<< Updated upstream
Esta linea es de configuracion de GIT que has hecha un stash o algo asi creo, no deberia estar

2020-09-15 13:53 UTC, JustAntoRS commented on src/bot.py
> +>>>>>>> Stashed changes
Lo mismo aqui, esta linea no deberia estar aqui

2020-09-18 20:36 UTC, JustAntoRS approved these changes
No hay test y tampoco hay doc en dynamic-channels.py pero bueno, hacemos merge y despues lo agregamos.

2020-09-18 20:42 UTC, merged