Issue 3 polls
acmfi/discord-bot pull request #26
Opened 2020-08-21 23:27 UTC by onmax

ANTES DE MERGEAR: [Resolver esto](https://github.com/acmfi/discord-bot/commit/441713fade28e8bdbf763b0b2bbbf59b6c1f773d#r42459460)

Ya está la estructura básica para las encuestas con la arquitectura que hemos decidido y con los comentarios. El código se puede ver  en la [issue 3](https://github.com/acmfi/discord-bot/issues/11).

@JustAntoRS Ya está listo para mergear. Creearé un nuevo issue con una lista de bugs y mejoras (como la de los gráficos). Pero esta primera versión está bastante completa para versión alpha del bot.

2020-09-10 14:31 UTC, JustAntoRS commented
He visto que estas lanzando excepciones en varias partes del codigo:
1. Tendria sentido crear nuestras propias excepciones? Igual es mas facil de hacer debug con excepciones propias
2. No he visto que las trates (en los test si), si se lanza una de las excepciones en la ejecucion del bot que ocurre? Se para la ejecucion y es el administrado el que tiene que ver que ha ocurrido? O la ejecucion continua pero esa operacion falla?

2020-09-10 16:24 UTC, JustAntoRS commented
Hecho en falta comentarios en las funciones, igual deberiamos usar algun sistema estandar de documentacion? 

Yo he usado [sphinx](https://www.sphinx-doc.org/en/master/) y a mi me gusta mucho, opiniones?

2020-09-12 16:05 UTC, onmax commented
> He visto que estas lanzando excepciones en varias partes del codigo:
> 
> 1. Tendria sentido crear nuestras propias excepciones? Igual es mas facil de hacer debug con excepciones propias
> 2. No he visto que las trates (en los test si), si se lanza una de las excepciones en la ejecucion del bot que ocurre? Se para la ejecucion y es el administrado el que tiene que ver que ha ocurrido? O la ejecucion continua pero esa operacion falla?

1. Creo que ahora he creado para todos los casos de error excepciones propias. Aunque seguro que se pueden añadir más en algún sitio
2. Si una excepción ocurre es muy posible que sea culpa del usuario por lo que se le envía la ayuda del comando y la ejecución continua. Puede darse el caso de que salte una excepción ajena al usuario y este reciba la ayuda incluso habiendo invocado al comando correctamente, pero esto creo que puede ocurrir un porcentaje muy bajo de las veces.

2020-09-12 16:13 UTC, JustAntoRS commented
>     1. Creo que ahora he creado para todos los casos de error excepciones propias. Aunque seguro que se pueden añadir más en algún sitio
> 
>     2. Si una excepción ocurre es muy posible que sea culpa del usuario por lo que se le envía la ayuda del comando y la ejecución continua. Puede darse el caso de que salte una excepción ajena al usuario y este reciba la ayuda incluso habiendo invocado al comando correctamente, pero esto creo que puede ocurrir un porcentaje muy bajo de las veces.

Okay, thanks por la explicacion, no habia visto que cuando una excepcion saltara se le enviara ayuda al usuario, parece correcto por mi lado.

2020-09-12 16:20 UTC, JustAntoRS requested changes
Varios comentarios generales sobre el fifhcero `poll.py` 

1. Es un fichero de 400 lineas con 4 o 5 clases dentro, lo veo demasiado, creo que es mejor hacer mas ficheros y que cada fichero tenga una clase. Es mejor tener 10 ficheros de 20 lineas que 1 uno de 200

2. Echo en falta mucha documentacion, al menos de los argumentos de las funciones, de que tipo se espera que sean, que formato se espera que tengan, que representan, etc etc

2020-09-12 16:20 UTC, JustAntoRS commented on src/extensions/poll.py
> +class InvalidInputException(Exception):
No me gusta tener muchas clases en el mismo fichero, aunque sean clases tontas como estas.

Creo que seria mejor tener una carpeta para excepceiones y un fichero para cada una de ellasy asi podemos documentar mas facilmente en que situaciones se lanza cada excepcion.

2020-09-12 16:20 UTC, JustAntoRS commented on src/extensions/poll.py
> +class InvalidFlagException(Exception):
Mis comentario que con la anterior clase que hereda de `Exception` en el mismo fichero.

2020-09-12 16:20 UTC, JustAntoRS commented on src/extensions/poll.py
> +    def __init__(self, short, unicode):
Me gustaria tener documentacion, el minimo minimo es documentar de que tipo es cada argumento y que formato se espera que tengan.

2020-09-12 17:05 UTC, onmax commented on src/extensions/poll.py
> +class InvalidInputException(Exception):
Ok, tengo pensado crear varios archivos y dividir todo mucho más, lo haré cuando comente el código

2020-09-12 17:05 UTC, onmax commented on src/extensions/poll.py
> +    def __init__(self, short, unicode):
No

2020-09-13 20:06 UTC, JustAntoRS commented on src/extensions/poll.py
> +    def __init__(self, short, unicode):
Si

2020-09-20 18:56 UTC, onmax commented on src/extensions/poll.py
> +    def __init__(self, short, unicode):
Listo @JustAntoRS

2020-10-15 14:39 UTC, JustAntoRS approved these changes
La acepto y merge porque lleva abierta la vida y es culpa mia.

Me molesta que en poll.py haya tantas clases, me gusta mas una clase por archivo.

2020-10-15 14:47 UTC, merged