#1 Implentación todavía sin aplicar el modelo MVC y sin tests
acmfi/discord-bot pull request #32
Opened 2020-09-12 00:36 UTC by xiaopeng-ye

- He añadido un fichero en formato json para poner todas las configuraciones sobre el bot
```json
{
    "token": "token del bot de discord",
    "channels_id": [
        "Primer ID (id's de los canales para recibir avisos enviados por el canal de telegram)",
        "Segundo ID"
    ],
    "api_users": [
        {
            "user": "nombre de usuario 1 (array de todo los usuarios que puedan usar el API)",
            "password": "contraseña"
        },
        {
            "user": "nombre de usuario 2",
            "password": "contraseña 2"
        }
    ]
}
```
- La funcionalidad de que solo usuarios con el nombre y la contraseña predefinidas y puestos en común puedan usar el servicio API
- Pipenv con las nuevas librerias necesarias instaladas
- Borrado los ficheros token y otros tipo txt (en mi caso) y el fichero del bot de telegram (ubicado en el nuevo repositorio)
- Apartado de la cofiguración sobre el fichero src/bot_conf.json en el README.md

2020-09-12 16:10 UTC, JustAntoRS requested changes
Cambios propuestos antes de hacer merge

2020-09-12 16:10 UTC, JustAntoRS commented on src/Extensions/resendpost.py
> +                image.close()
```suggestion
                with open('anuncio.png', 'wb+') as image:  
                    image.write(image_byte)
```
Es nitpick, pero en este caso creo que es mejor usar with si solo vas a hacer un write (el with cierra el archivo cuando acaba)

2020-09-12 16:10 UTC, JustAntoRS commented on src/Extensions/resendpost.py
> +    def __init__(self, bot, post_queue):
Agradeceria documentacion en el costructor, para saber de que tipos es cada argumento que recibe y que formato debe tener para funcionar correctamente

2020-09-12 16:10 UTC, JustAntoRS commented on src/apiserver.py
> +def run(post_queue: Queue):
Si vas a usar aqui definicion de tipos de forma `post_queue : Queue` usala en todos los sitios.

2020-09-12 16:10 UTC, JustAntoRS commented on src/bot.py
> +bot.CONF = json.load(open('src/bot_conf.json', 'r'))
```suggestion
with open('src/bot_conf.json', 'r') as conf_file:
    bot.CONF = json.load(conf_file) 
```

Asi el fichero se `bot_conf.json` se cierra tras ejecutar la asignacion.

2020-09-12 20:13 UTC, xiaopeng-ye commented
Ya he realizado los cambios

2020-09-13 11:51 UTC, JustAntoRS approved these changes

2020-09-13 11:59 UTC, merged